From 902792b674f7d20e2015c4ffe0d68dfef74ce6e5 Mon Sep 17 00:00:00 2001
From: Pierre Riteau <priteau@uchicago.edu>
Date: Mon, 10 Jul 2017 16:52:44 +0100
Subject: [PATCH] Customize error message on authentication failure

---
 openstack_auth/plugin/base.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/openstack_auth/plugin/base.py b/openstack_auth/plugin/base.py
index f1aff52..94c8bc3 100644
--- a/openstack_auth/plugin/base.py
+++ b/openstack_auth/plugin/base.py
@@ -13,6 +13,7 @@
 import abc
 import logging
 
+from django.utils.safestring import mark_safe
 from django.utils.translation import ugettext_lazy as _
 from keystoneauth1 import exceptions as keystone_exceptions
 from keystoneclient.v2_0 import client as v2_client
@@ -132,7 +133,8 @@ class BasePlugin(object):
                 keystone_exceptions.Forbidden,
                 keystone_exceptions.NotFound) as exc:
             LOG.debug(str(exc))
-            raise exceptions.KeystoneAuthException(_('Invalid credentials.'))
+            msg = _(mark_safe('Invalid credentials.<br />Please see <a href="https://www.chameleoncloud.org/docs/user-faq/">our User FAQ</a> for help.'))
+            raise exceptions.KeystoneAuthException(msg)
         except (keystone_exceptions.ClientException,
                 keystone_exceptions.AuthorizationFailure) as exc:
             msg = _("An error occurred authenticating. "
-- 
2.13.2

